QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civil', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelance', payment = 10 } } },
	bus = { label = 'Colectivero', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chofer', payment = 50 } } },
	judge = { label = 'Juez Honorario', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Juez', payment = 100 } } },
	lawyer = { label = 'Estudio Jurídico', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Asociado', payment = 50 } } },
	reporter = { label = 'Periodista', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Cronista', payment = 50 } } },
	trucker = { label = 'Camionero', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Conductor', payment = 50 } } },
	tow = { label = 'Grúa', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Operador', payment = 50 } } },
	garbage = { label = 'Recolección', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Recolector', payment = 50 } } },
	vineyard = { label = 'Viñedo', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Cosechador', payment = 50 } } },
	hotdog = { label = 'Panchero', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Ventas', payment = 50 } } },

	police = {
		label = 'Policía',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Cadete', payment = 50 },
			['1'] = { name = 'Oficial', payment = 75 },
			['2'] = { name = 'Sargento', payment = 100 },
			['3'] = { name = 'Teniente', payment = 125 },
			['4'] = { name = 'Jefe', isboss = true, payment = 150 },
		},
	},
	ambulance = {
		label = 'Emergencias Médicas',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 50 },
			['1'] = { name = 'Paramédico', payment = 75 },
			['2'] = { name = 'Médico', payment = 100 },
			['3'] = { name = 'Cirujano', payment = 125 },
			['4'] = { name = 'Jefe', isboss = true, payment = 150 },
		},
	},
	realestate = {
		label = 'Inmobiliaria',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 50 },
			['1'] = { name = 'Ventas de casas', payment = 75 },
			['2'] = { name = 'Ventas corporativas', payment = 100 },
			['3'] = { name = 'Broker', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 50 },
			['1'] = { name = 'Conductor', payment = 75 },
			['2'] = { name = 'Chofer de eventos', payment = 100 },
			['3'] = { name = 'Ventas', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Concesionario',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 50 },
			['1'] = { name = 'Ventas salón', payment = 75 },
			['2'] = { name = 'Ventas corporativas', payment = 100 },
			['3'] = { name = 'Finanzas', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 50 },
			['1'] = { name = 'Aprendiz', payment = 75 },
			['2'] = { name = 'Mecánico', payment = 100 },
			['3'] = { name = 'Especialista', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	mechanic2 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 50 },
			['1'] = { name = 'Aprendiz', payment = 75 },
			['2'] = { name = 'Mecánico', payment = 100 },
			['3'] = { name = 'Especialista', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = 'LS Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 50 },
			['1'] = { name = 'Aprendiz', payment = 75 },
			['2'] = { name = 'Mecánico', payment = 100 },
			['3'] = { name = 'Especialista', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 50 },
			['1'] = { name = 'Aprendiz', payment = 75 },
			['2'] = { name = 'Mecánico', payment = 100 },
			['3'] = { name = 'Especialista', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recluta', payment = 50 },
			['1'] = { name = 'Aprendiz', payment = 75 },
			['2'] = { name = 'Mecánico', payment = 100 },
			['3'] = { name = 'Especialista', payment = 125 },
			['4'] = { name = 'Gerente', isboss = true, payment = 150 },
		},
	},
}
